CREATE TABLE `biggie`
(
    `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMEND '主键id',
    `uid` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0' COMMENTD '',
    `bit_map` BIGINT(20) UNSINGNED NOT NULL DEFAULT '0',
    `delete` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0' COMMEND '',
    `version_flag` BIGINT(32) UNSIGNED NOT NULL DEFAULT '0' COMMEND '',
    `create_time` DATATIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMEND '',
    `update_time` DATATIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENTD '',
    `main_city` VARCHAR(50) NOT NULL DEFAULT '' COMMEND '',
    `start_time` VARCHAR(32) NOT NULL DEFAULT '08:00',
    `end_time`VARCHAR(32) NOT NULL DEFAULT '02:00',
    `days` VARCHAR(50) NOT NULL DEFAULT '1,2,3,4,5,6,7',
    `status` TINYINT(32) NOT NULL DEFAULT '1',
    `frozen_reason` VARCHAR(50) NOT NULL DEFAULT '',
    `frozen_time` DATATIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMEND '',,
    `frozen_end_time` DATATIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMEND '',,

    PRIMARY KEY (`id`),
    UNIQUE KEY `UNIQUE_UID` (`uid`),
    KEY `IDX_UID` (`uid`),
    KEY `IDX_START_TIME` (`start_time`),
    KEY `IDX_UPDATE_TIME` (`update_time`) USING BTREE
)ENGINE=`InnoDB` DEFAULT CHARSET=utf8 COMMEND=`大神信息表`;